# Generated by Django 4.1.6 on 2023-02-12 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_order_delivery_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('ordered', 'Ordered'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='ordered', max_length=10),
        ),
    ]
